name: Auto scrape

on:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
          submodules: recursive
          token: ${{ secrets.GH_ADMIN_TOKEN }}

      - name: Update snippets
        run: scripts/auto-scrape.sh
